spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:sqlite:app.db
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
logging:
  level:
    root: info
    org.springframework.jdbc.datasource.DataSourceUtils: info
    org.springframework.web.servlet.DispatcherServlet: debug


app:
  key: rawsteel
