### Register
POST http://localhost:8080/api/users/register
Content-Type: application/x-www-form-urlencoded

username=apple&password=apple

### Login
POST http://localhost:8080/api/users/login
Content-Type: application/x-www-form-urlencoded

username=apple&password=apple

### Current user
GET http://localhost:8080/api/users/current
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcHBsZSJ9.HyUzvHSCvGeTU0Pi8yr-PdTzWH96ngnA85b1sfRiLm4

### Current user without login
GET http://localhost:8080/api/users/current
Accept: application/json

###

